package main

import (
	"io/ioutil"
	"log"
)

// When tlsproxy is runned as a service by another app the app needs to know the configuration generated by ssh run.localhost
// This function will create a sample file $HOME/.ssh/.tunneled with the data required by the app.
// Sample .tunneled :
// The process id is:8484
// 68077d543caae5.localhost.run tunneled with tls termination, https://68077d543caae5.localhost.run
func createTunneledFile() error {
	// Returns $HOME/.ssh/.tunneled or error
	filename, created := sshTunneledInfoFile()
	if created != nil {
		return created
	}

	// Data Sample
	ds := "The process id is:8484\n68077d543caae5.localhost.run tunneled with tls termination, https://68077d543caae5.localhost.run"

	// Create $HOME/.ssh/.tunneled with data or error
	err := ioutil.WriteFile(filename, []byte(ds), 0755)
	if err != nil {
		log.Printf("Unable to write file: %v", err)
		return err
	}
	log.Printf("%s successfully created", filename)
	return nil
}
